/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {10, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[40] = 
  {10, 10, 0, 0, 0, 0, 1, 2,
  3, 9, 15, 21, 27, 0, 1, 2,
  3, 4, 5, 7, 8, 9, 3, 4,
  5, 6, 8, 9, 3, 4, 5, 6,
  7, 9, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s5[23] = 
  {10, 10, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s6[22] = 
  {10, 4, 0, 3, 7, 11, 15, 3,
  4, 5, 6, 7, 8, 9, 6, 7,
  8, 9, 6, 7, 8, 9};

/* quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u:(i0[10],i1[10],i2[4],i3[0],i4[],i5[0])->(o0[10],o1[10x10,27nz],o2[10x10,10nz],o3[10x4,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=2.7600000000000001e+01;
  a02=arg[2]? arg[2][0] : 0;
  a01=(a01*a02);
  a02=1.1439999999999999e+00;
  a01=(a01/a02);
  a02=2.;
  a03=arg[0]? arg[0][6] : 0;
  a04=arg[0]? arg[0][8] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][7] : 0;
  a07=arg[0]? arg[0][9] : 0;
  a08=(a06*a07);
  a05=(a05+a08);
  a05=(a02*a05);
  a08=(a01*a05);
  a00=(a00-a08);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a08=(a06*a04);
  a09=(a03*a07);
  a08=(a08-a09);
  a08=(a02*a08);
  a09=(a01*a08);
  a00=(a00-a09);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a09=9.8100000000000005e+00;
  a10=casadi_sq(a07);
  a11=casadi_sq(a03);
  a10=(a10-a11);
  a11=casadi_sq(a06);
  a10=(a10-a11);
  a11=casadi_sq(a04);
  a10=(a10+a11);
  a11=(a01*a10);
  a09=(a09+a11);
  a00=(a00-a09);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a09=5.0000000000000000e-01;
  a11=arg[2]? arg[2][1] : 0;
  a12=(a07*a11);
  a13=arg[2]? arg[2][2] : 0;
  a14=(a04*a13);
  a12=(a12-a14);
  a14=arg[2]? arg[2][3] : 0;
  a15=(a06*a14);
  a12=(a12+a15);
  a12=(a09*a12);
  a00=(a00-a12);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a12=(a04*a11);
  a15=(a07*a13);
  a12=(a12+a15);
  a15=(a03*a14);
  a12=(a12-a15);
  a12=(a09*a12);
  a00=(a00-a12);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a12=(a03*a13);
  a15=(a06*a11);
  a12=(a12-a15);
  a15=(a07*a14);
  a12=(a12+a15);
  a12=(a09*a12);
  a00=(a00-a12);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a12=(a03*a11);
  a15=(a06*a13);
  a12=(a12+a15);
  a15=(a04*a14);
  a12=(a12+a15);
  a12=(a09*a12);
  a00=(a00+a12);
  if (res[0]!=0) res[0][9]=a00;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a00=(a02*a04);
  a00=(a01*a00);
  a00=(-a00);
  if (res[1]!=0) res[1][3]=a00;
  a12=(a02*a07);
  a12=(a01*a12);
  if (res[1]!=0) res[1][4]=a12;
  a15=(a03+a03);
  a15=(a01*a15);
  if (res[1]!=0) res[1][5]=a15;
  a14=(a09*a14);
  if (res[1]!=0) res[1][6]=a14;
  a13=(a09*a13);
  a15=(-a13);
  if (res[1]!=0) res[1][7]=a15;
  a11=(a09*a11);
  if (res[1]!=0) res[1][8]=a11;
  a12=(-a12);
  if (res[1]!=0) res[1][9]=a12;
  if (res[1]!=0) res[1][10]=a00;
  a00=(a06+a06);
  a00=(a01*a00);
  if (res[1]!=0) res[1][11]=a00;
  a00=(-a14);
  if (res[1]!=0) res[1][12]=a00;
  if (res[1]!=0) res[1][13]=a11;
  if (res[1]!=0) res[1][14]=a13;
  a12=(a02*a03);
  a12=(a01*a12);
  a16=(-a12);
  if (res[1]!=0) res[1][15]=a16;
  a02=(a02*a06);
  a02=(a01*a02);
  a02=(-a02);
  if (res[1]!=0) res[1][16]=a02;
  a16=(a04+a04);
  a16=(a01*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][17]=a16;
  if (res[1]!=0) res[1][18]=a13;
  a11=(-a11);
  if (res[1]!=0) res[1][19]=a11;
  if (res[1]!=0) res[1][20]=a14;
  if (res[1]!=0) res[1][21]=a02;
  if (res[1]!=0) res[1][22]=a12;
  a12=(a07+a07);
  a01=(a01*a12);
  a01=(-a01);
  if (res[1]!=0) res[1][23]=a01;
  if (res[1]!=0) res[1][24]=a11;
  if (res[1]!=0) res[1][25]=a15;
  if (res[1]!=0) res[1][26]=a00;
  a00=1.;
  if (res[2]!=0) res[2][0]=a00;
  if (res[2]!=0) res[2][1]=a00;
  if (res[2]!=0) res[2][2]=a00;
  if (res[2]!=0) res[2][3]=a00;
  if (res[2]!=0) res[2][4]=a00;
  if (res[2]!=0) res[2][5]=a00;
  if (res[2]!=0) res[2][6]=a00;
  if (res[2]!=0) res[2][7]=a00;
  if (res[2]!=0) res[2][8]=a00;
  if (res[2]!=0) res[2][9]=a00;
  a00=2.4125874125874127e+01;
  a05=(a00*a05);
  a05=(-a05);
  if (res[3]!=0) res[3][0]=a05;
  a08=(a00*a08);
  a08=(-a08);
  if (res[3]!=0) res[3][1]=a08;
  a00=(a00*a10);
  a00=(-a00);
  if (res[3]!=0) res[3][2]=a00;
  a07=(a09*a07);
  a07=(-a07);
  if (res[3]!=0) res[3][3]=a07;
  a04=(a09*a04);
  a00=(-a04);
  if (res[3]!=0) res[3][4]=a00;
  a06=(a09*a06);
  if (res[3]!=0) res[3][5]=a06;
  a09=(a09*a03);
  if (res[3]!=0) res[3][6]=a09;
  if (res[3]!=0) res[3][7]=a04;
  if (res[3]!=0) res[3][8]=a07;
  a03=(-a09);
  if (res[3]!=0) res[3][9]=a03;
  if (res[3]!=0) res[3][10]=a06;
  a06=(-a06);
  if (res[3]!=0) res[3][11]=a06;
  if (res[3]!=0) res[3][12]=a09;
  if (res[3]!=0) res[3][13]=a07;
  if (res[3]!=0) res[3][14]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadcopter_ode_model_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
